"""add reusable learning cases

Revision ID: 54dbafbbdb0c
Revises: f22e07cd96ac
Create Date: 2026-09-04 18:23:02.393891
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "54dbafbbdb0c"
down_revision: str | Sequence[str] | None = "f22e07cd96ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("industry", sa.String(length=200), nullable=True),
        sa.Column("organization_scale", sa.String(length=200), nullable=True),
        sa.Column("challenge", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("intervention", sa.Text(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("lessons", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("reusable", sa.Boolean(), nullable=False),
        sa.Column("reusable_summary", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("learning_cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_learning_cases_industry"), ["industry"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_learning_cases_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_learning_cases_reusable"), ["reusable"], unique=False)
        batch_op.create_index(batch_op.f("ix_learning_cases_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_learning_cases_title"), ["title"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("learning_cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_learning_cases_title"))
        batch_op.drop_index(batch_op.f("ix_learning_cases_status"))
        batch_op.drop_index(batch_op.f("ix_learning_cases_reusable"))
        batch_op.drop_index(batch_op.f("ix_learning_cases_project_id"))
        batch_op.drop_index(batch_op.f("ix_learning_cases_industry"))

    op.drop_table("learning_cases")
    # ### end Alembic commands ###
