"""initial enterprise insight schema

Revision ID: 74cf2e16a0c8
Revises:
Create Date: 2026-09-04 18:07:46.251692
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "74cf2e16a0c8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("industry", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_companies_name"), ["name"], unique=False)

    op.create_table(
        "model_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("base_url", sa.String(length=1000), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("encrypted_api_key", sa.Text(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "name", name="uq_project_company_name"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_projects_status"), ["status"], unique=False)

    op.create_table(
        "action_definitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_type_key", sa.String(length=64), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("preconditions", sa.JSON(), nullable=False),
        sa.Column("effects", sa.JSON(), nullable=False),
        sa.Column("execution_mode", sa.String(length=32), nullable=False),
        sa.Column("risk_level", sa.String(length=32), nullable=False),
        sa.Column("require_approval", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "key", name="uq_action_definition_key"),
    )
    with op.batch_alter_table("action_definitions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_action_definitions_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_action_definitions_status"), ["status"], unique=False)

    op.create_table(
        "agent_threads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("agent_kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("trashed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_threads", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_threads_agent_kind"), ["agent_kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_threads_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "change_sets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("base_revision", sa.Integer(), nullable=False),
        sa.Column("operations", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("validation", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("change_sets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_change_sets_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_change_sets_status"), ["status"], unique=False)

    op.create_table(
        "entities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("type_key", sa.String(length=64), nullable=False),
        sa.Column("stable_key", sa.String(length=200), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("viewpoint", sa.String(length=32), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "stable_key", name="uq_entity_stable_key"),
    )
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_entities_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_entities_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_entities_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_entities_type_key"), ["type_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_entities_viewpoint"), ["viewpoint"], unique=False)

    op.create_table(
        "event_occurrences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("type_key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("participants", sa.JSON(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("event_occurrences", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_event_occurrences_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_event_occurrences_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_event_occurrences_type_key"), ["type_key"], unique=False
        )

    op.create_table(
        "export_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column("request_payload", sa.JSON(), nullable=False),
        sa.Column("download_url", sa.String(length=1000), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("export_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_export_jobs_project_id"), ["project_id"], unique=False)

    op.create_table(
        "hypotheses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("type_key", sa.String(length=100), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("participant_entity_ids", sa.JSON(), nullable=False),
        sa.Column("supporting_facts", sa.JSON(), nullable=False),
        sa.Column("counter_evidence", sa.JSON(), nullable=False),
        sa.Column("alternative_explanations", sa.JSON(), nullable=False),
        sa.Column("uncertainties", sa.JSON(), nullable=False),
        sa.Column("validation_questions", sa.JSON(), nullable=False),
        sa.Column("extension_payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("module_id", sa.String(length=200), nullable=True),
        sa.Column("module_version", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("hypotheses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_hypotheses_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_hypotheses_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_hypotheses_type_key"), ["type_key"], unique=False)

    op.create_table(
        "import_previews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("detected_encoding", sa.String(length=32), nullable=True),
        sa.Column("columns", sa.JSON(), nullable=False),
        sa.Column("sample_rows", sa.JSON(), nullable=False),
        sa.Column("all_rows", sa.JSON(), nullable=False),
        sa.Column("suggested_mapping", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_previews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_import_previews_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_import_previews_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "ontology_releases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "version", name="uq_ontology_release"),
    )
    with op.batch_alter_table("ontology_releases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ontology_releases_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "ontology_types",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_type_key", sa.String(length=64), nullable=True),
        sa.Column("interface_keys", sa.JSON(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("relation_roles", sa.JSON(), nullable=False),
        sa.Column("action_parameters", sa.JSON(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "key", name="uq_ontology_type_key"),
    )
    with op.batch_alter_table("ontology_types", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ontology_types_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ontology_types_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "publications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("project_revision", sa.Integer(), nullable=False),
        sa.Column("ontology_release_id", sa.String(length=36), nullable=True),
        sa.Column("graph_snapshot", sa.JSON(), nullable=False),
        sa.Column("entity_count", sa.Integer(), nullable=False),
        sa.Column("relation_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "version", name="uq_publication_version"),
    )
    with op.batch_alter_table("publications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_publications_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "relations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("type_key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("viewpoint", sa.String(length=32), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("relations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_relations_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_relations_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_relations_type_key"), ["type_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_relations_viewpoint"), ["viewpoint"], unique=False)

    op.create_table(
        "scenarios",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("assumptions", sa.JSON(), nullable=False),
        sa.Column("overlay_operations", sa.JSON(), nullable=False),
        sa.Column("expected_benefits", sa.JSON(), nullable=False),
        sa.Column("risks", sa.JSON(), nullable=False),
        sa.Column("validation_metrics", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scenarios", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scenarios_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scenarios_status"), ["status"], unique=False)

    op.create_table(
        "source_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_documents_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_source_documents_sha256"), ["sha256"], unique=False)

    op.create_table(
        "source_systems",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("connection_profile", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("source_systems", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_systems_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "agent_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("citations", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["agent_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_messages_thread_id"), ["thread_id"], unique=False
        )

    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("agent_kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("context_manifest", sa.JSON(), nullable=False),
        sa.Column("result_message_id", sa.String(length=36), nullable=True),
        sa.Column("change_set_id", sa.String(length=36), nullable=True),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["agent_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_runs_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_runs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_runs_thread_id"), ["thread_id"], unique=False)

    op.create_table(
        "evidence_fragments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_document_id", sa.String(length=36), nullable=False),
        sa.Column("locator", sa.String(length=500), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["source_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence_fragments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_fragments_source_document_id"),
            ["source_document_id"],
            unique=False,
        )

    op.create_table(
        "hypothesis_feedback",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("hypothesis_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("provided_by", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["hypothesis_id"], ["hypotheses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("hypothesis_feedback", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_hypothesis_feedback_hypothesis_id"), ["hypothesis_id"], unique=False
        )

    op.create_table(
        "relation_participants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("relation_id", sa.String(length=36), nullable=False),
        sa.Column("role_key", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["relation_id"], ["relations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "relation_id", "role_key", "entity_id", "ordinal", name="uq_relation_participant"
        ),
    )
    with op.batch_alter_table("relation_participants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_relation_participants_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_relation_participants_relation_id"), ["relation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_relation_participants_role_key"), ["role_key"], unique=False
        )

    op.create_table(
        "semantic_mappings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("source_system_id", sa.String(length=36), nullable=False),
        sa.Column("source_asset", sa.String(length=500), nullable=False),
        sa.Column("source_field", sa.String(length=500), nullable=False),
        sa.Column("target_type_key", sa.String(length=64), nullable=False),
        sa.Column("target_property_key", sa.String(length=64), nullable=False),
        sa.Column("transform_expression", sa.Text(), nullable=True),
        sa.Column("authority_priority", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_system_id"], ["source_systems.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("semantic_mappings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_semantic_mappings_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_semantic_mappings_source_system_id"), ["source_system_id"], unique=False
        )

    op.create_table(
        "action_invocations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("action_definition_id", sa.String(length=36), nullable=False),
        sa.Column("source_agent_run_id", sa.String(length=36), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("requested_by", sa.String(length=100), nullable=False),
        sa.Column("target_entity_ids", sa.JSON(), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("preflight", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("approved_by", sa.String(length=100), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_definition_id"], ["action_definitions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_agent_run_id"], ["agent_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "idempotency_key", name="uq_action_invocation_idempotency"
        ),
    )
    with op.batch_alter_table("action_invocations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_action_invocations_action_definition_id"),
            ["action_definition_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_action_invocations_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_action_invocations_source_agent_run_id"),
            ["source_agent_run_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_action_invocations_status"), ["status"], unique=False)

    op.create_table(
        "claims",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("fragment_id", sa.String(length=36), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("predicate", sa.String(length=200), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["fragment_id"], ["evidence_fragments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_claims_fragment_id"), ["fragment_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_claims_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_claims_status"), ["status"], unique=False)

    op.create_table(
        "action_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("invocation_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=True),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["invocation_id"], ["action_invocations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("action_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_action_logs_invocation_id"), ["invocation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_action_logs_project_id"), ["project_id"], unique=False)

    op.create_table(
        "action_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("invocation_id", sa.String(length=36), nullable=False),
        sa.Column("metric_key", sa.String(length=200), nullable=False),
        sa.Column("observed_value", sa.JSON(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["invocation_id"], ["action_invocations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("action_observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_action_observations_invocation_id"), ["invocation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_action_observations_project_id"), ["project_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("action_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_observations_project_id"))
        batch_op.drop_index(batch_op.f("ix_action_observations_invocation_id"))

    op.drop_table("action_observations")
    with op.batch_alter_table("action_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_logs_project_id"))
        batch_op.drop_index(batch_op.f("ix_action_logs_invocation_id"))

    op.drop_table("action_logs")
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claims_status"))
        batch_op.drop_index(batch_op.f("ix_claims_project_id"))
        batch_op.drop_index(batch_op.f("ix_claims_fragment_id"))

    op.drop_table("claims")
    with op.batch_alter_table("action_invocations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_invocations_status"))
        batch_op.drop_index(batch_op.f("ix_action_invocations_source_agent_run_id"))
        batch_op.drop_index(batch_op.f("ix_action_invocations_project_id"))
        batch_op.drop_index(batch_op.f("ix_action_invocations_action_definition_id"))

    op.drop_table("action_invocations")
    with op.batch_alter_table("semantic_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_semantic_mappings_source_system_id"))
        batch_op.drop_index(batch_op.f("ix_semantic_mappings_project_id"))

    op.drop_table("semantic_mappings")
    with op.batch_alter_table("relation_participants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_relation_participants_role_key"))
        batch_op.drop_index(batch_op.f("ix_relation_participants_relation_id"))
        batch_op.drop_index(batch_op.f("ix_relation_participants_entity_id"))

    op.drop_table("relation_participants")
    with op.batch_alter_table("hypothesis_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hypothesis_feedback_hypothesis_id"))

    op.drop_table("hypothesis_feedback")
    with op.batch_alter_table("evidence_fragments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_fragments_source_document_id"))

    op.drop_table("evidence_fragments")
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_runs_thread_id"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_status"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_project_id"))

    op.drop_table("agent_runs")
    with op.batch_alter_table("agent_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_messages_thread_id"))

    op.drop_table("agent_messages")
    with op.batch_alter_table("source_systems", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_systems_project_id"))

    op.drop_table("source_systems")
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_documents_sha256"))
        batch_op.drop_index(batch_op.f("ix_source_documents_project_id"))

    op.drop_table("source_documents")
    with op.batch_alter_table("scenarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scenarios_status"))
        batch_op.drop_index(batch_op.f("ix_scenarios_project_id"))

    op.drop_table("scenarios")
    with op.batch_alter_table("relations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_relations_viewpoint"))
        batch_op.drop_index(batch_op.f("ix_relations_type_key"))
        batch_op.drop_index(batch_op.f("ix_relations_status"))
        batch_op.drop_index(batch_op.f("ix_relations_project_id"))

    op.drop_table("relations")
    with op.batch_alter_table("publications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_publications_project_id"))

    op.drop_table("publications")
    with op.batch_alter_table("ontology_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ontology_types_project_id"))
        batch_op.drop_index(batch_op.f("ix_ontology_types_kind"))

    op.drop_table("ontology_types")
    with op.batch_alter_table("ontology_releases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ontology_releases_project_id"))

    op.drop_table("ontology_releases")
    with op.batch_alter_table("import_previews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_previews_project_id"))
        batch_op.drop_index(batch_op.f("ix_import_previews_expires_at"))

    op.drop_table("import_previews")
    with op.batch_alter_table("hypotheses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hypotheses_type_key"))
        batch_op.drop_index(batch_op.f("ix_hypotheses_status"))
        batch_op.drop_index(batch_op.f("ix_hypotheses_project_id"))

    op.drop_table("hypotheses")
    with op.batch_alter_table("export_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_export_jobs_project_id"))

    op.drop_table("export_jobs")
    with op.batch_alter_table("event_occurrences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_occurrences_type_key"))
        batch_op.drop_index(batch_op.f("ix_event_occurrences_project_id"))
        batch_op.drop_index(batch_op.f("ix_event_occurrences_occurred_at"))

    op.drop_table("event_occurrences")
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entities_viewpoint"))
        batch_op.drop_index(batch_op.f("ix_entities_type_key"))
        batch_op.drop_index(batch_op.f("ix_entities_status"))
        batch_op.drop_index(batch_op.f("ix_entities_project_id"))
        batch_op.drop_index(batch_op.f("ix_entities_name"))

    op.drop_table("entities")
    with op.batch_alter_table("change_sets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_change_sets_status"))
        batch_op.drop_index(batch_op.f("ix_change_sets_project_id"))

    op.drop_table("change_sets")
    with op.batch_alter_table("agent_threads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_threads_project_id"))
        batch_op.drop_index(batch_op.f("ix_agent_threads_agent_kind"))

    op.drop_table("agent_threads")
    with op.batch_alter_table("action_definitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_definitions_status"))
        batch_op.drop_index(batch_op.f("ix_action_definitions_project_id"))

    op.drop_table("action_definitions")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_status"))
        batch_op.drop_index(batch_op.f("ix_projects_company_id"))

    op.drop_table("projects")
    op.drop_table("model_profiles")
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_companies_name"))

    op.drop_table("companies")
    # ### end Alembic commands ###
