"""link imports to source systems

Revision ID: f22e07cd96ac
Revises: 74cf2e16a0c8
Create Date: 2026-09-04 18:12:41.287019
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f22e07cd96ac"
down_revision: str | Sequence[str] | None = "74cf2e16a0c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("import_previews", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_system_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_import_previews_source_system_id"), ["source_system_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_import_previews_source_system_id",
            "source_systems",
            ["source_system_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_system_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_source_documents_source_system_id"), ["source_system_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_source_documents_source_system_id",
            "source_systems",
            ["source_system_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.drop_constraint("fk_source_documents_source_system_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_source_documents_source_system_id"))
        batch_op.drop_column("source_system_id")

    with op.batch_alter_table("import_previews", schema=None) as batch_op:
        batch_op.drop_constraint("fk_import_previews_source_system_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_import_previews_source_system_id"))
        batch_op.drop_column("source_system_id")

    # ### end Alembic commands ###
