/**
 * @deprecated The old release page duplicated the advanced-tools surface and
 * was never routed. Keep this compatibility export for downstream imports;
 * the application has one authoritative developer surface now.
 */
export { AdvancedToolsPage as DataReleasePage } from "./AdvancedToolsPage";

/*

  const refresh = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["source-systems", projectId] }), queryClient.invalidateQueries({ queryKey: ["semantic-mappings", projectId] }), queryClient.invalidateQueries({ queryKey: ["change-sets", projectId] }), queryClient.invalidateQueries({ queryKey: ["publications", projectId] })]); await refreshWorkspace(); };
  const systemMutation = useMutation({ mutationFn: (input: SourceSystemCreate) => api.createSourceSystem(projectId, input), onSuccess: async (system) => { setNotice(`系统源“${system.name}”已登记。`); await refresh(); }, onError: (value) => setError(value) });
  const systemTestMutation = useMutation({ mutationFn: (id: string) => api.testSourceSystem(projectId, id), onSuccess: async (test) => { setNotice(`${test.ok ? "连接成功" : "连接失败"}：${test.message}`); await refresh(); }, onError: (value) => setError(value) });
  const mappingMutation = useMutation({ mutationFn: (input: SemanticMappingCreate) => api.createSemanticMapping(projectId, input), onSuccess: async () => { setNotice("语义映射草稿已保存，请校验并批准后再用于导入。"); await refresh(); }, onError: (value) => setError(value) });
  const mappingCommandMutation = useMutation({ mutationFn: ({ mapping, command }: { mapping: SemanticMapping; command: "validate" | "approve" | "disable" }) => command === "validate" ? api.validateSemanticMapping(projectId, mapping.id, { expected_revision: mapping.revision }) : command === "approve" ? api.approveSemanticMapping(projectId, mapping.id, { expected_revision: mapping.revision }) : api.disableSemanticMapping(projectId, mapping.id, { expected_revision: mapping.revision }), onSuccess: async (mapping) => { setNotice(`语义映射状态已更新为 ${mapping.status}。`); await refresh(); }, onError: (value) => setError(value) });
  const changeSetMutation = useMutation({ mutationFn: (input: { title: string; description: string | null; operations: ChangeOperation[] }) => api.createChangeSet(projectId, { ...input, base_revision: projectRevision, created_by: "developer" }), onSuccess: async (item) => { setSelectedChangeSetId(item.id); setNotice(`变更集“${item.title}”已创建。`); await refresh(); }, onError: (value) => setError(value) });
  const changeCommandMutation = useMutation({ mutationFn: ({ item, command }: { item: ChangeSet; command: "validate" | "approve" | "apply" }) => command === "validate" ? api.validateChangeSet(projectId, item.id) : command === "approve" ? api.approveChangeSet(projectId, item.id) : api.applyChangeSet(projectId, item.id), onSuccess: async (item, variables) => { setNotice(`${commandLabel(variables.command)}完成，变更集状态：${item.status}。`); await refresh(); await queryClient.invalidateQueries({ queryKey: ["change-preview", projectId, item.id] }); }, onError: (value) => setError(value) });
  const publishMutation = useMutation({ mutationFn: ({ label, notes }: { label: string; notes: string | null }) => api.publishProject(projectId, { label, notes, expected_project_revision: projectRevision }), onSuccess: async (publication) => { setNotice(`正式版本 ${publication.version} 已发布。`); await refresh(); }, onError: (value) => setError(value) });
  const exportMutation = useMutation({ mutationFn: () => api.createExport(projectId, { format: "json", include_evidence: true, include_lineage: true, filters: {}, release_id: null }), onSuccess: (job) => { setExportUrl(job.download_url); setNotice(job.download_url ? "导出文件已生成。" : `导出任务状态：${job.status}`); }, onError: (value) => setError(value) });

  const createSystem = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { systemMutation.mutate({ name: String(form.get("name")).trim(), kind: String(form.get("kind")) as SourceSystemKind, description: String(form.get("description") ?? "").trim() || null, connection_profile: parseObject(String(form.get("connection_profile") ?? "{}")) }); event.currentTarget.reset(); } catch (value) { setError(asError(value)); } };
  const createMapping = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const input: SemanticMappingCreate = { source_system_id: String(form.get("source_system_id")), source_asset: String(form.get("source_asset")).trim(), source_field: String(form.get("source_field")).trim(), target_type_key: String(form.get("target_type_key")), target_property_key: String(form.get("target_property_key")).trim(), transform_expression: String(form.get("transform_expression") ?? "").trim() || null, authority_priority: Number(form.get("authority_priority") || 100) }; if (!input.source_system_id || !input.source_asset || !input.source_field || !input.target_type_key || !input.target_property_key) { setError(new Error("请填写完整的来源字段和目标语义。")); return; } mappingMutation.mutate(input); };
  const createChangeSet = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const parsed = JSON.parse(String(form.get("operations") || "[]")) as unknown; if (!Array.isArray(parsed)) throw new Error("变更操作必须是 JSON 数组。"); changeSetMutation.mutate({ title: String(form.get("title")).trim(), description: String(form.get("description") ?? "").trim() || null, operations: parsed as ChangeOperation[] }); } catch (value) { setError(asError(value)); } };
  const publish = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); publishMutation.mutate({ label: String(form.get("label")).trim(), notes: String(form.get("notes") ?? "").trim() || null }); };
  const runCommand = (command: "validate" | "approve" | "apply") => { if (selectedChangeSet) changeCommandMutation.mutate({ item: selectedChangeSet, command }); };

  return <div className="page-stack">
    <section className="page-hero"><div><p className="eyebrow">ALIGN & RELEASE</p><h1>数据对齐与发布</h1><p>系统字段先映射到本体语义，再通过变更校验进入正式企业投影。</p></div><button className="button primary" onClick={onPreview}>预览当前草稿</button></section>
    {notice && <StatusMessage title="操作结果" description={notice} />}
    {error && <StatusMessage tone="danger" title="操作没有完成" description={error.message} action={{ label: "关闭", onClick: () => setError(null) }} />}
    <div className="data-release-grid">
      <section className="panel"><div className="panel-heading"><div><h2>系统源</h2><p>登记 ERP、MES、CRM、数据库、接口或文件来源。</p></div><span>{systemsQuery.data?.total ?? 0} 个</span></div><div className="compact-list">{(systemsQuery.data?.items ?? []).map((system) => <article key={system.id}><div><strong>{system.name}</strong><small>{system.kind} · {system.status}{system.last_tested_at ? ` · ${formatDate(system.last_tested_at)}` : ""}</small></div><button className="button text-button" disabled={systemTestMutation.isPending} onClick={() => systemTestMutation.mutate(system.id)}>测试连接</button></article>)}{!systemsQuery.data?.items.length && <p className="empty-copy">没有系统数据的企业可以暂时跳过这里。</p>}</div><form className="create-form" onSubmit={createSystem}><h3>登记系统源</h3><div className="form-grid-two"><label>名称<input name="name" required placeholder="例如：销售 CRM" /></label><label>类型<select name="kind" defaultValue="ERP">{sourceKinds.map((kind) => <option key={kind}>{kind}</option>)}</select></label></div><label>说明<textarea name="description" rows={2} /></label><label>连接配置 JSON<textarea name="connection_profile" rows={4} defaultValue="{}" spellCheck={false} /></label><button className="button secondary" disabled={systemMutation.isPending}>保存系统源</button></form></section>
      <section className="panel"><div className="panel-heading"><div><h2>语义映射</h2><p>把系统表字段对齐到本体类型和属性；只有已批准映射会参与导入。</p></div><span>{mappingsQuery.data?.total ?? 0} 条</span></div><div className="compact-list mapping-list">{(mappingsQuery.data?.items ?? []).map((mapping) => <article key={mapping.id}><div><strong>{mapping.source_asset}.{mapping.source_field}</strong><small>→ {mapping.target_type_key}.{mapping.target_property_key} · {mapping.status}</small></div><div className="row-actions"><span className="tag">优先级 {mapping.authority_priority}</span>{mapping.status === "DRAFT" && <button className="button text-button" disabled={mappingCommandMutation.isPending} onClick={() => mappingCommandMutation.mutate({ mapping, command: "validate" })}>校验</button>}{mapping.status === "VALIDATED" && <button className="button text-button" disabled={mappingCommandMutation.isPending} onClick={() => mappingCommandMutation.mutate({ mapping, command: "approve" })}>批准</button>}{mapping.status !== "DISABLED" && <button className="button text-button danger-text" disabled={mappingCommandMutation.isPending} onClick={() => mappingCommandMutation.mutate({ mapping, command: "disable" })}>停用</button>}</div></article>)}{!mappingsQuery.data?.items.length && <p className="empty-copy">登记系统源后建立第一条字段映射。</p>}</div><form className="create-form" onSubmit={createMapping}><h3>新建映射</h3><label>来源系统<select name="source_system_id" required defaultValue=""><option value="" disabled>请选择</option>{(systemsQuery.data?.items ?? []).map((system) => <option key={system.id} value={system.id}>{system.name}</option>)}</select></label><div className="form-grid-two"><label>来源资产/表<input name="source_asset" required placeholder="orders" /></label><label>来源字段<input name="source_field" required placeholder="customer_id" /></label></div><label>目标本体类型<select name="target_type_key" required defaultValue=""><option value="" disabled>请选择</option>{(typesQuery.data?.items ?? []).map((type) => <option key={type.id} value={type.key}>{type.name}（{type.key}）</option>)}</select></label><div className="form-grid-two"><label>目标属性<input name="target_property_key" required placeholder="customer_id" /></label><label>权威优先级<input name="authority_priority" type="number" defaultValue="100" /></label></div><label>转换表达式（可选）<input name="transform_expression" placeholder="strip|int" /></label><button className="button secondary" disabled={!systemsQuery.data?.total || mappingMutation.isPending}>保存映射草稿</button></form></section>
    </div>
    <section className="panel"><div className="panel-heading"><div><h2>变更集</h2><p>Agent 或开发者提出的变更先预览和校验，再审批、应用。</p></div><span>项目修订 {projectRevision}</span></div><div className="change-set-layout"><div className="change-set-list">{(changeSetsQuery.data?.items ?? []).map((item) => <button key={item.id} className={selectedChangeSet?.id === item.id ? "selected" : ""} onClick={() => setSelectedChangeSetId(item.id)}><span><strong>{item.title}</strong><small>{item.status} · 基于修订 {item.base_revision}</small></span><span>{item.operations?.length ?? 0} 项</span></button>)}{!changeSetsQuery.data?.items.length && <p className="empty-copy">还没有变更集。Agent 的建模提案也会进入这里。</p>}</div><div className="change-preview">{selectedChangeSet && changePreviewQuery.data ? <><div className="subsection-heading"><h3>{selectedChangeSet.title}</h3><span>{selectedChangeSet.status}</span></div><div className="preview-counts"><span>新建 <strong>{changePreviewQuery.data.creates}</strong></span><span>修改 <strong>{changePreviewQuery.data.updates}</strong></span><span>退役 <strong>{changePreviewQuery.data.retires}</strong></span></div><div className="validation-box"><strong>{changePreviewQuery.data.validation.valid ? "校验通过" : "存在校验问题"}</strong>{changePreviewQuery.data.validation.issues.map((issue, index) => <p key={index}>{issue.code}：{issue.message}</p>)}</div><div className="command-toolbar"><button className="button secondary" disabled={!['DRAFT','INVALID'].includes(selectedChangeSet.status) || changeCommandMutation.isPending} onClick={() => runCommand("validate")}>校验</button><button className="button secondary" disabled={selectedChangeSet.status !== 'VALID' || changeCommandMutation.isPending} onClick={() => runCommand("approve")}>审批</button><button className="button primary" disabled={selectedChangeSet.status !== 'APPROVED' || changeCommandMutation.isPending} onClick={() => runCommand("apply")}>应用</button></div></> : <div className="empty-copy">选择变更集查看预览。</div>}</div></div><form className="create-form change-set-form" onSubmit={createChangeSet}><h3>手动建立变更集</h3><div className="form-grid-two"><label>标题<input name="title" required /></label><label>说明<input name="description" /></label></div><label>操作 JSON 数组<textarea name="operations" rows={6} defaultValue="[]" spellCheck={false} /></label><button className="button secondary" disabled={changeSetMutation.isPending}>创建变更集</button></form></section>
    <section className="panel publish-panel"><div className="panel-heading"><div><h2>正式发布与导出</h2><p>正式版本供管理层查看；导出包含证据与血缘。</p></div><span>{publicationsQuery.data?.total ?? 0} 个版本</span></div><div className="publish-layout"><div className="publication-list">{(publicationsQuery.data?.items ?? []).map((publication) => <article key={publication.id}><strong>v{publication.version} · {publication.label}</strong><small>修订 {publication.project_revision} · {publication.entity_count} 对象 / {publication.relation_count} 关系 · {formatDate(publication.created_at)}</small></article>)}{!publicationsQuery.data?.items.length && <p className="empty-copy">尚未发布正式版本。</p>}</div><form className="create-form" onSubmit={publish}><h3>发布当前修订</h3><label>版本名称<input name="label" required placeholder="例如：管理层基线版" /></label><label>发布说明<textarea name="notes" rows={2} /></label><div className="button-row"><button type="button" className="button secondary" disabled={exportMutation.isPending} onClick={() => exportMutation.mutate()}>导出 JSON</button><button className="button primary" disabled={publishMutation.isPending}>正式发布</button></div>{exportUrl && <a className="download-link" href={exportUrl}>下载导出文件</a>}</form></div></section>
  </div>;
}

function parseObject(value: string): Record<string, unknown> { const parsed = JSON.parse(value || "{}"); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("连接配置必须是 JSON 对象。"); return parsed as Record<string, unknown>; }
function asError(value: unknown) { return value instanceof Error ? value : new Error("输入无法解析。"); }
function commandLabel(command: "validate" | "approve" | "apply") { return ({ validate: "校验", approve: "审批", apply: "应用" })[command]; }
function formatDate(value: string) { return new Intl.DateTimeFormat("zh-CN", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
*/
